[build-system]
requires = ["setuptools>=69.0"]
build-backend = "setuptools.build_meta"

[project]
name = "repoguardian-ai"
version = "0.1.0"
description = "AI-powered Pull Request Review Agent using LangChain, LangGraph and LlamaIndex"
readme = "README.md"
requires-python = ">=3.11"

authors = [
    { name = "Gagan Meena" }
]

dependencies = [
    # LangChain
    "langchain==0.3.27",
    "langchain-community==0.3.27",
    "langchain-core==0.3.72",
    "langchain-ollama==0.3.6",

    # LangGraph
    "langgraph==0.6.5",

    # LlamaIndex
    "llama-index==0.13.2",

    # GitHub
    "PyGithub==2.8.1",

    # Embeddings
    "sentence-transformers==5.1.0",
    "faiss-cpu==1.11.0.post1",

    # HTTP
    "httpx==0.28.1",
    "requests==2.32.5",

    # Config
    "python-dotenv==1.1.1",
    "pydantic==2.11.7",
    "pydantic-settings==2.10.1",

    # CLI / Logging
    "rich==14.1.0",
    "typer==0.17.3",

    # Git
    "GitPython==3.1.45",
]

[project.optional-dependencies]
dev = [
    "pytest==8.4.1",
    "pytest-cov==6.2.1",
    "black==25.1.0",
    "ruff==0.12.9"
]

[tool.setuptools]
py-modules = [
    "main",
    "config",
    "github_client",
    "rag",
    "llm",
    "reviewer",
    "prompts"
]

[tool.black]
line-length = 100

[tool.ruff]
line-length = 100

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]